export const {
  VITE_GITLAB_CLIENT_ID: GITLAB_CLIENT_ID,
  VITE_GITLAB_CLIENT_SECRET: GITLAB_CLIENT_SECRET,
  VITE_GITLAB_REDIRECT_URI: GITLAB_REDIRECT_URI,
  VITE_GITLAB_BASE_URL: GITLAB_BASE_URL,
  VITE_GITLAB_API_URL: GITLAB_API_URL,
  VITE_GITLAB_PROJECT_ID: GITLAB_PROJECT_ID
} = import.meta.env
